volumes:
  bitpingd-volume:
  
services:
  bitping:
    image: bitping/bitpingd:latest
    container_name: bitping
    stdin_open: true
    tty: true
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - bitpingd-volume:/root/.bitpingd

  honeygain:
    image: honeygain/honeygain:latest
    container_name: honeygain
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    command: >
      -tou-accept
      -email "${HONEYGAIN_EMAIL}"
      -pass "${HONEYGAIN_PASSWORD}"
      -device "${DEVICE_NAME}"

  packetstream:
    image: packetstream/psclient:latest
    container_name: psclient
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - CID=${PS_CLIENT_CID}

  pawns:
    image: iproyal/pawns-cli:latest
    container_name: pawns
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    command: >
      -accept-tos
      -email="${PAWNS_EMAIL}"
      -password="${PAWNS_PASSWORD}"
      -device-name="${DEVICE_NAME}"

  traffmonetizer:
    image: traffmonetizer/cli_v2:latest
    container_name: traffmonetizer
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    command: >
      -i
      --name tm
      traffmonetizer/cli_v2
      start
      accept
      --token "${TRAFFMONETIZER_TOKEN}"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_API_VERSION=1.44
    command: >
      --cleanup
      --include-stopped
      --include-restarting
      --revive-stopped
      --interval 3600
      honeygain
      packetstream
      pawns
      traffmonetizer
    depends_on:
      - honeygain
      - packetstream
      - pawns
      - traffmonetizer

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - "127.0.0.1:8080:8080"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml